### ISSUE TITLE
0.7.1 is missing on PyPi

### ISSUE THREAD

**Issue by frenck** [home-assistant-ecosystem/python-luftdaten#11]
Hi there 👋 

The 0.7.1 release is marked here on GitHub:

https://github.com/home-assistant-ecosystem/python-luftdaten/releases/tag/0.7.1

But seems to miss on PyPi:

![image](https://user-images.githubusercontent.com/195327/144298200-45b7af36-f60d-4ac4-bd98-eab583dbeeaf.png)

Any possibility that we can see that version (with the relaxed `httpx` requirement), to show up on PyPi?

Thanks!

../Frenck

**Comment by fabaff** [comment]
Is now available: https://pypi.org/project/luftdaten/0.7.1/

Thanks

**Comment by frenck** [comment]
Thanks for the quick turnaround, appreciated ❤️
